### PR TITLE
Fixed tests suite

### PR DESCRIPTION
**Pull request by clash82**
This PR is the same as  https://github.com/ezsystems/MarketingAutomationBundle/pull/7.
I had to create a new PR because I've lost access to my previous fork (rebase was required).

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by clash82** [comment]
@bdunogier can you approve it again? :)

**Comment by andrerom** [comment]
It's the same PR, so implicit he did :)

**Comment by clash82** [comment]
I just wanted to make sure 😋

**Pull request merged**
