### PR TITLE
Added .travis.yml file

### PR DESCRIPTION
**Pull request by clash82**

### CODE REVIEW

**Comment by clash82** [comment]
ping @andrerom

**Comment by clash82** [comment]
@andrerom can you enable travis on this repo?

**Comment by clash82** [comment]
I don't want to be annoying but... you know... :)
ping @andrerom @bdunogier

**Comment by andrerom** [comment]
So we need hook, on it

**Comment by clash82** [comment]
> So we need hook, on it
Can you also set hook for Packagist?

**Comment by andrerom** [comment]
yes I did ;) you can amend and force push to trigger travis

**Comment by clash82** [comment]
close/reopen - it's much faster :) thank you

**Comment by andrerom** [comment]
true :)

**Comment by clash82** [comment]
passed, yippee 🎉

**Comment by SylvainGuittard** [comment]
Good job :)

**Comment by clash82** [comment]
Thank you, Sir 👮

**Pull request merged**
